# Generated by Django 6.0.3 on 2026-06-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemanager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagemanager/images/'),
        ),
    ]
