# Generated by Django 6.0.3 on 2026-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_imagemanager_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='imagemanager/documents/')),
            ],
        ),
    ]
