# Generated by Django 6.0.3 on 2026-06-07 17:31

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_documentmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmanager',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=users.models.upload_path_doc),
        ),
        migrations.AlterField(
            model_name='imagemanager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_path_img),
        ),
    ]
